--
- name: Add key
  ansible.builtin.apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.sury.org/php/ bullseye main
    state: present

- name: Install LAMP
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - apache2
    - mariadb-server
    - mariadb-client
    - php8.0
    - libapache2-mod-php8.0
    - php8.0-mysql
    - php8.0-curl
    - php8.0-xml
    - php8.0-zip
    - php8.0-mbstring
    - php8.0-intl
    - php8.0-opcache
    - php8.0-imagick
    - php8.0-gd
    - php8.0-cli
    - php8.0-fpm
    - libapache2-mod-fcgid
    - wget
    - unzip
    - python3
    - python3-pip

- name: Enable service apache2 and mariadb
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - apache2
    - mariadb
  changed_when: false

- name: Enable the Apache2 module
  community.general.apache2_module:
    name: "{{ item }}"  
    state: present
  with_items:
    - headers
    - rewrite
    - proxy
    - proxy_fcgi
    - ssl
    - http2
    - expires

- name: Install PyMySQL python package
  ansible.builtin.pip:
    name: PyMySQL

- name: disable php8.0
  ansible.builtin.command: "a2dismod php8.0"
  changed_when: false

- name: enable php8.0-fpm
  ansible.builtin.command: "a2enconf php8.0-fpm"
  changed_when: false

- name: disable mpm_prefork
  ansible.builtin.command: "a2dismod mpm_prefork"
  changed_when: false

- name: enable mpm_event
  ansible.builtin.command: "a2enmod mpm_event"
  changed_when: false

- name: Copy security config
  ansible.builtin.template:
    src: "security.conf.j2"
    dest: "/etc/apache2/conf-available/security.conf"
    owner: root
    group: root
    mode: '0744'

- name: Copy FPM php.ini
  ansible.builtin.template:
    src: "php.ini.j2"
    dest: "/etc/php/8.0/fpm/php.ini"
    owner: root
    group: root
    mode: '0744'
  notify:
    - Restart apache2
    - Restart php8.0-fpm

- name: Set my.cnf file
  ansible.builtin.template: 
    src: "my.cnf.j2" 
    dest: "/etc/mysql/my.cnf"
  notify:
    - Restart mariadb
